[package]
url = "https://www.x.org/releases/individual/xcb/xcb-util-cursor-0.1.5.tar.xz"
ref = "0.1.5"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libxcb-image@0.1.5", "xcb-util-renderutil@0.3.10"]
dev_dependencies = ["macros@1.20.2", "libtool@2.5.4"]

# Note:
# This library support linux only.
