[package]
url = "https://github.com/kmod-project/kmod.git"
ref = "v34.2"

[[build_configs]]
build_system = "meson"
dev_dependencies = [
    "pkgconf@2.4.3",
    "bash-completion@2.17.0",
    "fish-shell@4.1.2",
    "zstd@1.5.7",
]
dependencies = []
