[package]
url = "https://xkbcommon.org/download/libxkbcommon-1.6.0.tar.xz"
ref = "1.6.0"

[[build_configs]]
pattern = "*linux*"
patches = ["fix_cannot_find_wayland_scanner.patch"]
build_system = "meson"
envs = [
    "CFLAGS=-isystem ${DEPS_DIR}/include/libxml2",
    "CXXFLAGS=-isystem ${DEPS_DIR}/include/libxml2",
]
options = ["-Denable-bash-completion=false", "-Denable-docs=false"]
dependencies = [
    "libxcb@1.17.0",
    "libxml2@2.13.5",
    "libxdmcp@1.1.5",
    "wayland@1.23.1",
    "wayland-protocols@1.44",
]
dev_dependencies = ["wayland@1.23.1", "bison@3.8.2"]

# Note:
# This library support linux only.
