[package]
url = "https://www.zlib.net/zlib-1.3.1.tar.gz"
ref = "v1.3.1"

[[build_configs]]
build_system = "cmake"
options = ["-DZLIB_BUILD_EXAMPLES=OFF"]
post_install_windows = [
  "cmake -E rename ${PACKAGE_DIR}/lib/zlib.lib ${PACKAGE_DIR}/lib/z.lib",
]