[package]
url = "https://github.com/opencv/opencv.git"
ref = "4.11.0"

[[build_configs]]
build_system = "cmake"
options = [
    "-DENABLE_NEON=OFF",
    "-DBUILD_TESTING=OFF",
    "-DBUILD_DOCS=OFF",
    "-DBUILD_ANDROID_EXAMPLES=OFF",
    "-DBUILD_EXAMPLES=OFF",
    "-DBUILD_PERF_TESTS=OFF",
    "-DBUILD_TESTS=OFF",
    "-DWITH_FFMPEG=OFF",
    "-DWITH_GTK=OFF",
    "-DWITH_GSTREAMER=OFF",
]
