[package]
  url                 = "https://github.com/libatasmart/libatasmart.git"
  ref                 = "8cfe544"

[[build_configs]]
  build_system        = "meson" 
  dependencies        = ["libudev@1.8.2","libbsd@0.12.2"]
  dev_dependencies        = ["pkgconf@2.4.3","gtk-doc@4.17.6"]