[package]
url = "https://github.com/libatasmart/libatasmart.git"
ref = "master"

[[build_configs]]
dependencies = ["libudev@1.8.2", "libbsd@0.12.2", "libmd@1.1.0"]
build_system = "meson"
dev_dependencies = ["pkgconf@2.4.3", "gtk-doc@4.17.6"]
