[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libsm.git"
ref = "libSM-1.2.5"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libice@1.1.2"]
dev_dependencies = ["macros@1.20.2"]

# Note:
# This library support linux only.
