[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxcb-cursor.git"
ref = "xcb-util-cursor-0.1.5"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = [
    "libxcb-image@0.1.5",
    "xcb-util-renderutil@0.3.10",
]
dev_dependencies = ["macros@1.20.2", "gperf@3.1"]

# Note:
# This library support linux only.
