[package]
url = "https://github.com/guillemj/libmd.git"
ref = "1.1.0"

[[build_configs]]
build_system = "makefiles"
dependencies = []

pre_configure = ["cd ${REPO_DIR} && ./autogen"]

# Note:
# This library support linux only.