[package]
url = "https://gitlab.freedesktop.org/mesa/libdrm.git"
ref = "libdrm-2.4.124"

# ================ build for aarch64-linux ================ #
[[build_configs]]
pattern = "*linux*"
build_system = "meson"
dependencies = ["xcb-proto@1.17.0"]
dev_dependencies = ["pkgconf@2.4.3"]
options = ["-Dtests=false"]
# Note:
# This library support linux only.
