[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxkbfile.git"
ref = "libxkbfile-1.1.3"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libx11@1.8.11"]
dev_dependencies = ["macros@1.20.2"]

# Note:
# This library support linux only.