[package]
url = "https://github.com/mcatalancid/libudev.git"
ref = "1.8.2"

[[build_configs]]
build_system = "makefiles"
dev_dependencies = [
  "gtk-doc@4.17.6",
  "libtool@2.5.4",
  "pkgconf@2.4.3",
  "autoconf@2.72",
  "automake@1.18",
  "macros@1.20.2",
  "kmod@34.2",
]
dependencies = ["ncurses@6.5", "util-linux@2.41"]
