[package]
  url                 = "https://github.com/mcatalancid/libudev.git"
  ref                 = "1.8.2"

[[build_configs]]
  build_system        = "makefiles"
  dev_dependencies        = ["gtk-doc@4.17.6"]
  dependencies        = ["ncurses@6.5"]