[package]
  url                 = "https://github.com/mcatalancid/libudev.git"
  ref                 = "1.8.2"

[[build_configs]]
  build_system        = "makefiles"
  dependencies        = ["util-linux@2.41"]