[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git"
ref = "xcb-util-0.4.1"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["libxcb@1.17.0"]
dev_dependencies = ["macros@1.20.2", "libtool@2.5.4"]

# Note:
# This library support linux only.