[package]
url = "https://gitlab.freedesktop.org/wayland/wayland-protocols.git"
ref = "1.44"

[[build_configs]]
pattern = "*linux*"
build_system = "meson"
patches = [ "fix_cannot_find_wayland_scanner.patch"]
dependencies = ["wayland@1.23.1"]
dev_dependencies = ["pkgconf@2.4.3", "wayland@1.23.1"]

# Note:
# This library support linux only.
