[package]
url = "https://github.com/systemd/systemd.git"
ref = "v258.1"

[[build_configs]]
envs = [
    "CFLAGS=\"-I{DEPS_DIR}/include\"",
    "LDFLAGS=\"-L{DEPS_DIR}/lib\"",
    "CPPFLAGS=\"-I{DEPS_DIR}/include\"",
]
build_system = "meson"
dev_dependencies = ["gperf@3.1", "libcap@2.77", "util-linux@2.41"]
dependencies = ["libcap@2.77", "util-linux@2.41"]
