[package]
url = "https://download.qt.io/official_releases/qt/5.15/5.15.16/single/qt-everywhere-opensource-src-5.15.16.tar.xz"
ref = "5.15.16"

[[build_configs]]
pattern = "x86_64-linux*"
patches = ["add_linux-x86_64-gnu-g++.patch"]
build_system = "qmake"
options = [
    "-xplatform linux-x86_64-gnu-g++",
    "-sysroot ${SYSROOT}",
    "-extprefix ${PACKAGE_DIR}",
    "-confirm-license",
    "-opensource",
    "-optimize-size",
    "-static-runtime",
    "-xcb",
    "-fontconfig",
    "-dbus",
    "-openssl-linked",
    "-opengl desktop",
    "-bundled-xcb-xinput",
    "-make-tool make",
    "-nomake tests",
    "-nomake examples",
    "-skip qtdoc",
    "-skip qtwebengine",
]
dependencies = [
    "libxcb-cursor@0.1.5",
    "xcb-util-wm@0.4.2",
    "xcb-imdkit@1.0.8",
    "xcb-util-xrm@1.0",
    "mesa@18.3.6",
    "openssl@1.1.1w",
    "icu@75.1",
    "libjpeg@9f",
    "freetype@2.13.3",
    "libsm@1.2.5",
    "xorg-sgml-doctools@1.12.1",
    "libxkbcommon@1.6.0",
    "pthread-stubs@0.4",
    "libxcb-image@0.1.5",
    "xcb-util-renderutil@0.3.10",
    "xcb-util@0.4.1",
    "libxdmcp@1.1.5",
    "libxext@1.3.6",
    "libxfixes@6.0.1",
    "libxi@1.8.2",
    "libxrender@0.9.12",
    "libxtrans@1.5.2",
    "xorgproto@2024.1",
    "libdrm@2.4.124",
    "libxslt@1.1.42",
    "libxcursor@1.2.3",
    "libxcomposite@0.4.6",
    "libxdamage@1.1.6",
    "libxrandr@1.5.4",
    "libxscrnsaver@1.2.4",
    "libevent@2.1.12",
    "nss@3.55",
    "fontconfig@2.16.0",
    "pulseaudio@16.2",
    "zstd@1.5.7",
]

[[build_configs]]
pattern = "aarch64-linux*"
patches = ["fix_linux-aarch64-gnu-g++.patch"]
build_system = "qmake"
envs = [
    "OPENGL_INC_DIR=${DEPS_DIR}/include",
    "OPENGL_LIB_DIR=${DEPS_DIR}/lib",
]
options = [
    "-xplatform linux-aarch64-gnu-g++",
    "-sysroot ${SYSROOT}",
    "-extprefix ${PACKAGE_DIR}",
    "-confirm-license",
    "-opensource",
    "-optimize-size",
    "-static-runtime",
    "-xcb",
    "-fontconfig",
    "-dbus",
    "-openssl-linked",
    "-opengl es2",
    "-bundled-xcb-xinput",
    "-make-tool make",
    "-nomake tests",
    "-nomake examples",
    "-skip qtdoc",
    "-skip qtwebengine",
]
dependencies = [
    "libxcb-cursor@0.1.5",
    "xcb-util-wm@0.4.2",
    "xcb-imdkit@1.0.8",
    "xcb-util-xrm@1.0",
    "mesa@18.3.6",
    "openssl@1.1.1w",
    "icu@75.1",
    "libjpeg@9f",
    "freetype@2.13.3",
    "libsm@1.2.5",
    "xorg-sgml-doctools@1.12.1",
    "libxkbcommon@1.6.0",
    "pthread-stubs@0.4",
    "libxcb-image@0.1.5",
    "xcb-util-renderutil@0.3.10",
    "xcb-util@0.4.1",
    "libxdmcp@1.1.5",
    "libxext@1.3.6",
    "libxfixes@6.0.1",
    "libxi@1.8.2",
    "libxrender@0.9.12",
    "libxtrans@1.5.2",
    "xorgproto@2024.1",
    "libdrm@2.4.124",
    "libxslt@1.1.42",
    "libxcursor@1.2.3",
    "libxcomposite@0.4.6",
    "libxdamage@1.1.6",
    "libxrandr@1.5.4",
    "libxscrnsaver@1.2.4",
    "libevent@2.1.12",
    "nss@3.55",
    "fontconfig@2.16.0",
    "pulseaudio@16.2",
    "zstd@1.5.7",
]
