[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxcursor.git"
ref = "libXcursor-1.2.3"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = [
    "xorgproto@2024.1",
    "libx11@1.8.11",
    "libxfixes@6.0.1",
    "libxrender@0.9.12",
]
dev_dependencies = ["macros@1.20.2"]

# Note:
# This library support linux only.
