[package]
url = "https://archive.mozilla.org/pub/security/nss/releases/NSS_3_55_RTM/src/nss-3.55.tar.gz"
ref = "3.55"
src_dir = "nss"

# ============== build for aarch64-linux ============ #
[[build_configs]]
pattern = "aarch64-linux*"
patches = ["nss-standalone-1.patch"]
build_system = "gyp"
build_tools = ["python-is-python3"] # Create symblink python to python3.
dependencies = ["sqlite3@3.49.0", "zlib@1.3.1", "nspr@4.36"]
dev_dependencies = ["nspr@4.36"]
options = [
    "-v",
    "-g",
    "--disable-tests",
    "--with-nspr=${DEPS_DIR}/include/nspr:${DEPS_DIR}/lib",
    "--target=aarch64",
    "-Duse_hw_aes=1",
    "-Duse_arm_neon=1",
    "-Dsign_libs=0",
]

# ============== build for x86_64-linux ============ #
[[build_configs]]
pattern = "x86_64-linux*"
patches = ["nss-standalone-1.patch"]
build_system = "gyp"
build_tools = ["python-is-python3"] # Create symblink python to python3.
dependencies = ["sqlite3@3.49.0", "zlib@1.3.1", "nspr@4.36"]
dev_dependencies = ["nspr@4.36"]
options = [
    "-v",
    "-g",
    "--disable-tests",
    "--with-nspr=${DEPS_DIR}/include/nspr:${DEPS_DIR}/lib",
    "--target=x86_64",
    "-Duse_hw_aes=1",
    "-Duse_arm_neon=1",
    "-Dsign_libs=0",
]

# Note:1
# This library support linux only.