[package]
url = "https://github.com/openssl/openssl.git"
ref = "openssl-3.5.0"

# ============= build for aarch64-linux =========== #
[[build_configs]]
pattern = "aarch64-linux*"
build_system = "makefiles"
build_shared = "shared"
build_static = "no-shared"
options = [
    "linux-aarch64",
    "no-docs",
    "no-demos",
    "no-tests",
    "--openssldir=ssl",
    "--libdir=lib"
]

# ============= build for x86_64-linux =========== #
[[build_configs]]
pattern = "x86_64-linux*"
build_system = "makefiles"
build_shared = "shared"
build_static = "no-shared"
dev_dependencies = ["nasm@2.16.03"]
options = [
    "linux-x86_64",
    "no-docs",
    "no-demos",
    "no-tests",
    "--openssldir=ssl",
    "--libdir=lib"
]

# ============= build for windows =========== #
[[build_configs]]
pattern = "*windows*"
build_system = "makefiles"
build_tools = ["perl"]
build_shared = "shared"
build_static = "no-shared"
dev_dependencies = ["nasm@2.16.03"]
options = [
    "VC-WIN64A",
    "no-docs",
    "no-demos",
    "no-tests",
    "--openssldir=ssl",
    "--libdir=lib"
]
