[package]
  url                 = "https://github.com/ompl/ompl.git"
  ref                 = "v1.7.0"

[[build_configs]]
  build_system        = "cmake" 
  dependencies        = []
  pre_configure       = []
  dev_dependencies        = []