[package]
url = "https://gitlab.freedesktop.org/xorg/lib/libxdmcp.git"
ref = "libXdmcp-1.1.5"

[[build_configs]]
pattern = "*linux*"
build_system = "makefiles"
dependencies = ["xorgproto@2024.1"]
dev_dependencies = [
    "macros@1.20.2",
    "libtool@2.5.4",
]

# Note:
# This library support linux only.
